// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Sensor struct {
	ID         int32              `json:"id"`
	SensorName string             `json:"sensor_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SensorMetadatum struct {
	ID               int32              `json:"id"`
	SensorType       pgtype.Text        `json:"sensor_type"`
	Manufacturer     pgtype.Text        `json:"manufacturer"`
	ModelNumber      pgtype.Text        `json:"model_number"`
	SensorLocation   pgtype.Text        `json:"sensor_location"`
	InstallationTime pgtype.Timestamptz `json:"installation_time"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AdditionalData   []byte             `json:"additional_data"`
	SensorID         int32              `json:"sensor_id"`
}

type SensorReading struct {
	ReadingTimestamp pgtype.Timestamptz `json:"reading_timestamp"`
	SensorID         pgtype.Int4        `json:"sensor_id"`
	Temperature      pgtype.Float8      `json:"temperature"`
	Humidity         pgtype.Float8      `json:"humidity"`
	Pressure         pgtype.Float8      `json:"pressure"`
}
